### ISSUE TITLE
Count and expanded collections

### ISSUE THREAD

**Issue by hylkevds** [OGC-IoT/ogc-iot-api#35]
When $count is specified, or enabled by default, should $expand-ed collections also get a count? In the returned json there is no place to put it. Or does it become something like Observations@iot.count ?

The same goes for the @iot.nextLink of expanded sub-collections.

btw, the count and nextLink propertynames are incorrect in http://www.sensorup.com/docs/#get83

**Comment by tkhalafbeigi** [comment]
$count=true enables the count for the main entity type but not the expanded ones. If you want to enable count for expanded entity type you should use inline count query in the expand. For example, /Datastreams?$expand=Observations($count=true) enables the count for expanded Observations for each Datastream. In this case the count of expanded entity will be shown like Observations@iot.count=<count number> as you mentioned. It is the same for nextLink, in this case Observations@iot.nextLink contains the nextLink for expanded Observations inside each Datastream.
You can also use other query options inline to expand. Again example could be like /Datastreams?$expand=Observations($count=true;$top=10;$skip=1).
